apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-monolith
  labels:
    app: website
spec:
  replicas: 2 # Strict Assignment Requirement
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
        spec:
      containers:
      - name: website-container
        image: vishalup13/website-monolith:latest
        ports:
        - containerPort: 80
